function c=v3Defaults(overrides)
%V3DEFAULTS All finite search limits are expandable numerical approximations.
% Measured on the real ephemeris: completion_beam_width 1 (a width-4 beam added
% only ~12 targets per call, width 1 walks all 35 steps in ~32 s and reaches
% 31/35) and completion_seconds 30 (at 8 s a deep completion cannot finish, so
% complete candidates are never produced).
c=struct('seed',1,'budget_s',60,'beam_width',8,'root_count',4,'colony_count',2, ...
 'search_max_dv_km_s',6.1,'plane_change_threshold_deg',5,'plane_penalty_km_s',0.5,'plane_penalty_saturation',2, ...
 'rejected_proposal_factor',10,'cost_time_budget_factor',1.6, ...
 'cost_guidance_enabled',true,'cost_lookahead_s',43200,'cost_time_samples',6, ...
 'cost_time_weight_km_s',0.3,'policy_feedback_gain',1,'policy_penalty_ceiling',4, ...
 'cost_natural_windows',1,'cost_enumeration_fraction',0.65, ...
 'family_penalty_weight',1,'family_completion_weight',1.5, ...
 'family_completion_window',0.35,'phasing_pursuit_weight',0.5, ...
 'band_separation_km_s',0.35,'plane_separation_weight',0.02, ...
 'pheromone_floor',0.05,'work_family_quota',2, ...
 'target_plane_bin_deg',5,'arrival_shape_weight',0.35,'radial_tour_weight',0.7,'cost_refine_count',3, ...
 'actions_per_node',4,'beam_expansions',2,'completion_steps',35, ...
 'joint_seconds',12,'joint_iterations',15,'max_shooting_arc_s',7200, ...
 'completion_seconds',30,'guided_attempts',3,'guided_branches',3,'guided_distinct_targets',2, ...
 'completion_beam_width',1,'completion_outputs',4,'fresh_queue_size',16, ...
 'guided_keep',4,'time_grid_count',5,'time_refine_iterations',2, ...
 'time_refine_fraction',.15,'branch_greedy_probability',.5,'time_rank_power',2, ...
 'action_min_duration_s',.001,'guided_max_revolutions',6, ...
 'replan_enabled',true,'replan_probability',.5,'replan_seconds',8,'replan_cut_count',2,'replan_retry_limit',3, ...
 'restoration_fraction',0.65,'restoration_iterations',200,'joint_target_ids',1:35, ...
 'cold_completion_enabled',true,'cold_beam_width',4,'cold_durations_s',[900 1800 3600 7200], ...
 'prefix_restart_every',3, ...
 'prefix_memory_size',8,'prefix_pheromone_gain',2, ...
 'prefix_joint_seconds',3,'prefix_joint_every',3, ...
 'prefix_consistency_km',0.1, ...
 'fuel_algorithm','sparse_sqp', ...
 'projected_joint',true,'projected_step_radius',0.005, ...
 'connection_iterations',8,'connection_tolerance_km',1e-5, ...
 'mutation_difference_tolerances',[1e-3 1e-6 1e-3],'recovery_stall_limit',3, ...
 'guided_root_fraction',0.75,'root_wait_max_s',86400,'root_plane_tilts_deg',[0 15], ...
 'protected_root_every',2,'beam_seconds',4,'lineage_stall_limit',2, ...
 'consistency_stride',4,'fuel_trust_radius',1e-4,'mutation_scale',0.2,'wide_mutation_probability',0.25, ...
 'shooting_reltol',1e-13,'verify_reltol',3e-14,'max_step_s',120, ...
 'scan_step_s',300,'height_margin_km',0.01,'height_min_interval_s',0.01, ...
 'search_radius_km',0.99,'constraint_tolerance',1e-8, ...
 'max_maneuvers',48,'pulse_component_bound',20,'node_position_bound',2e6, ...
 'node_velocity_bound',100,'action_durations_s',[600 1800 7200 21600 86400], ...
 'random_pulse_scales',[0.02 0.2 1 4],'exploration',0.2, ...
 'pheromone_alpha',1,'heuristic_beta',1,'evaporation',0.1, ...
 'pheromone_baseline',1,'pheromone_ceiling',20,'pheromone_gain',2,'pheromone_cost_scale_km_s',1, ...
 'diversity_scales',[25 .025 500 .05 300 .01],'diversity_samples',9, ...
 'diversity_pulse_floor_km_s',1e-6,'diversity_event_tolerance_s',60, ...
 'beam_diversity_scales',[500 .1 1800], ...
 'pheromone_state_scales',[21600 1000 .25], ...
 'temperature_km_s',0.2,'cooling',0.97,'reheat_after',12, ...
 'expand_after',8,'archive_size',8,'checkpoint_every',1, ...
 'initial_candidates',{{}},'stop_file','','resume_file','');
if nargin<1, return; end
names=fieldnames(overrides);
assert(all(ismember(names,fieldnames(c))),'ctocscreen:v3:config','Unknown configuration field.');
for k=1:numel(names), c.(names{k})=overrides.(names{k}); end
positive={'budget_s','beam_width','root_count','colony_count','actions_per_node','beam_expansions', ...
 'plane_change_threshold_deg','plane_penalty_km_s','plane_penalty_saturation','cost_lookahead_s','cost_time_samples', ...
 'cost_time_weight_km_s','policy_feedback_gain','policy_penalty_ceiling','pheromone_floor','work_family_quota', ...
 'arrival_shape_weight','cost_refine_count','cost_natural_windows','cost_enumeration_fraction', ...
 'family_penalty_weight','family_completion_weight','phasing_pursuit_weight','band_separation_km_s','plane_separation_weight','target_plane_bin_deg', ...
 'rejected_proposal_factor','cost_time_budget_factor', ...
 'completion_beam_width','completion_outputs','fresh_queue_size','guided_keep','time_grid_count', ...
 'cold_beam_width','prefix_memory_size','prefix_pheromone_gain','prefix_restart_every', ...
 'time_refine_fraction','time_rank_power','action_min_duration_s','replan_seconds','replan_cut_count','replan_retry_limit', ...
 'projected_step_radius','connection_iterations','connection_tolerance_km', ...
 'protected_root_every','beam_seconds','lineage_stall_limit', ...
 'consistency_stride','fuel_trust_radius','mutation_scale', ...
 'prefix_consistency_km', ...
 'completion_seconds','guided_attempts','guided_branches','guided_distinct_targets','restoration_iterations','prefix_joint_seconds','prefix_joint_every', ...
 'completion_steps','joint_seconds','joint_iterations','max_shooting_arc_s', ...
 'shooting_reltol','verify_reltol','max_step_s','scan_step_s','height_margin_km', ...
 'height_min_interval_s','search_radius_km','constraint_tolerance','max_maneuvers', ...
 'pulse_component_bound','node_position_bound','node_velocity_bound','temperature_km_s', ...
 'reheat_after','expand_after','archive_size','checkpoint_every'};
for k=1:numel(positive), validateattributes(c.(positive{k}),{'double'},{'scalar','positive','finite'}); end
integer={'beam_width','root_count','colony_count','actions_per_node','beam_expansions', ...
 'cost_time_samples','work_family_quota','cost_refine_count','cost_natural_windows', ...
 'cold_beam_width','prefix_memory_size','prefix_restart_every', ...
 'completion_beam_width','completion_outputs','fresh_queue_size','guided_keep','time_grid_count','replan_cut_count','replan_retry_limit', ...
 'connection_iterations', ...
 'protected_root_every','lineage_stall_limit', ...
 'consistency_stride', ...
 'guided_attempts','guided_branches','guided_distinct_targets','restoration_iterations','prefix_joint_every', ...
 'completion_steps','joint_iterations','max_maneuvers','reheat_after','expand_after','archive_size','checkpoint_every'};
for k=1:numel(integer), validateattributes(c.(integer{k}),{'double'},{'integer'}); end
validateattributes(c.seed,{'double'},{'scalar','integer','nonnegative','finite'});
assert(c.restoration_fraction>0&&c.restoration_fraction<1);
assert(ismember(c.fuel_algorithm,{'sparse_sqp','sqp'}));
validateattributes(c.projected_joint,{'logical'},{'scalar'});
validateattributes(c.replan_enabled,{'logical'},{'scalar'});
validateattributes(c.cold_completion_enabled,{'logical'},{'scalar'});
validateattributes(c.cost_guidance_enabled,{'logical'},{'scalar'});
validateattributes(c.search_max_dv_km_s,{'double'},{'scalar','positive','real','nonnan'});
assert(c.pheromone_floor<c.pheromone_baseline);
assert(c.rejected_proposal_factor>=1);
assert(c.cost_enumeration_fraction<1);
assert(c.family_completion_window>0&&c.family_completion_window<=1);
assert(c.guided_root_fraction>=0&&c.guided_root_fraction<=1);
assert(c.mutation_scale<=1&&c.wide_mutation_probability>=0&&c.wide_mutation_probability<=1);
validateattributes(c.joint_target_ids,{'double'},{'vector','integer','>=',1,'<=',35});
assert(numel(unique(c.joint_target_ids))==numel(c.joint_target_ids));
assert(c.search_radius_km<=1 && c.exploration>0 && c.exploration<=1);
assert(c.cooling>0 && c.cooling<=1 && c.evaporation>0 && c.evaporation<1);
validateattributes(c.action_durations_s,{'double'},{'positive','finite','vector'});
validateattributes(c.cold_durations_s,{'double'},{'positive','finite','vector'});
validateattributes(c.random_pulse_scales,{'double'},{'nonnegative','finite','vector'});
validateattributes(c.recovery_stall_limit,{'double'},{'scalar','positive','finite','integer'});
validateattributes(c.mutation_difference_tolerances,{'double'},{'vector','numel',3,'positive','finite'});
validateattributes(c.diversity_scales,{'double'},{'vector','numel',6,'positive','finite'});
validateattributes(c.beam_diversity_scales,{'double'},{'vector','numel',3,'positive','finite'});
validateattributes(c.pheromone_state_scales,{'double'},{'vector','numel',3,'positive','finite'});
validateattributes(c.diversity_samples,{'double'},{'scalar','integer','>=',3,'finite'});
extra={'pheromone_baseline','pheromone_ceiling','pheromone_gain','pheromone_cost_scale_km_s', ...
 'diversity_pulse_floor_km_s','diversity_event_tolerance_s'};
for k=1:numel(extra), validateattributes(c.(extra{k}),{'double'},{'scalar','positive','finite'}); end
assert(c.pheromone_ceiling>c.pheromone_baseline);
validateattributes(c.time_refine_iterations,{'double'},{'scalar','integer','nonnegative','finite'});
validateattributes(c.guided_max_revolutions,{'double'},{'scalar','integer','nonnegative','finite'});
validateattributes(c.radial_tour_weight,{'double'},{'scalar','nonnegative','finite'});
validateattributes(c.root_wait_max_s,{'double'},{'scalar','nonnegative','finite'});
validateattributes(c.root_plane_tilts_deg,{'double'},{'vector','nonempty','nonnegative','finite','<',178});
assert(c.time_refine_fraction<1&&c.branch_greedy_probability>=0&&c.branch_greedy_probability<=1);
assert(c.replan_probability>=0&&c.replan_probability<=1);
end
