function s = v3PreprocessSignature()
%V3PREPROCESSSIGNATURE Sign inputs and executable preprocessing dependencies.
sim=fileparts(fileparts(fileparts(mfilename('fullpath'))));
atk=fullfile(fileparts(sim),'problem','ctoc14乙题','ATK-CTOC14');
files={fullfile(sim,'data','ctoc14b_targets.csv'), ...
 fullfile(fileparts(sim),'problem','ctoc14乙题','CTOC14B.atk'), ...
 fullfile(atk,'AstroData','Earth','EGM96.grv'), ...
 fullfile(atk,'AstroData','Earth','Earth.cb'), ...
 fullfile(atk,'AstroData','EOP-All.txt'), ...
 fullfile(atk,'AstroData','LeapSecond.dat'), ...
 fullfile(atk,'AstroData','IERS-conventions','2010','IAU2006_XYS.dat')};
names={'v3FileHash','v3PreprocessSignature','v3TargetModel','v3J2Acceleration', ...
 'v3NominalPole','v3BuildTargetEphemeris','v3QueryTargets','v3LoadTargetEphemeris','loadProblem','auditSource'};
for k=1:numel(names)
 files{end+1}=which(['ctocscreen.' names{k}]); %#ok<AGROW>
end
s.files=files; s.sha256=cell(size(files));
for k=1:numel(files), s.sha256{k}=ctocscreen.v3FileHash(files{k}); end
s.matlab_version=version;
end
