function root=v3PrefixRestart(item,eph)
%V3PREFIXRESTART Start at the epoch using an orbit learned in this run only.
q=item.initial_q;
s=struct('schema_version','free_maneuver_v3','dynamics_id','central_j2', ...
 'initial_q',q,'maneuver_times_s',zeros(0,1),'delta_v_km_s',zeros(0,3), ...
 'duration_s',1,'witness_times_s',nan(35,1),'validation_level','proposal', ...
 'root_key',sprintf('%.17g/',q));
root=struct('schedule',s,'t',0,'state',ctocscreen.initialState(q,eph.model.mu,eph.model.re), ...
 'visited',false(35,1),'J',0,'keys',{{}},'last_gain',0,'estimate',0, ...
 'seed_target',0,'seed_duration_s',NaN,'root_method','in_run_prefix_restart');
end
