function c=defaults(overrides)
%DEFAULTS Recorded numerical search limits, not competition constraints.
c=struct('seed',888,'budget_s',300,'root_count',4,'beam_width',16, ...
 'branch_count',2,'target_count',7,'time_samples',7,'max_revolutions',3, ...
 'lookahead_s',43200,'window_radius_s',2400,'discovery_radius_km',2500, ...
 'shared_attempts',3,'scope_seconds',[2 4 8],'joint_iterations',24, ...
 'full_every',5,'structure_every',4,'root_every',10,'max_maneuvers',60, ...
 'max_shooting_arc_s',21600,'trust_initial',0.03,'trust_max',0.3, ...
 'trust_min',1e-7,'penalty_initial',10,'penalty_max',1e6,'restoration_step_weight',1e-4, ...
 'search_radius_km',0.99,'height_margin_km',0.01, ...
 'height_min_interval_s',0.01,'scan_step_s',600, ...
 'shooting_reltol',1e-13,'verify_reltol',3e-14,'max_step_s',180, ...
 'defect_position_km',1e-5,'defect_velocity_km_s',1e-8, ...
 'restore_tolerance',1e-8,'eccentricity_limit',0.00099, ...
 'model_radius_km',0.98,'model_height_margin_km',1,'sma_margin_km',0.05, ...
 'rebase_limit',4,'rebase_gap_km',0.005, ...
 'solver_tolerance',1e-10,'subproblem_step_tolerance',1e-7,'solver_iterations',150,'solver_seconds',2, ...
 'search_max_dv_km_s',6.1,'notify_dv_km_s',8,'plane_threshold_deg',5, ...
 'plane_weight',0.5,'exploration',0.2,'negative_cap',4,'evaporation',0.1, ...
 'positive_capacity',6,'verify_reserve_s',18,'checkpoint_s',300,'action_seconds',7, ...
 'new_root_fraction',0.25,'max_zero_gain',3,'log_every',1, ...
 'event_window_s',172800,'event_grid_s',300,'coplanar_deg',2,'min_flight_s',600, ...
 'heuristic_weight',0.5,'heuristic_fraction',1,'event_candidates',24,'events_per_target',2, ...
 'departures_per_event',4,'grid_share',0.2,'heuristic_beta',2,'time_slack',0,'time_weight',4, ...
 'layer_diversity',0.5,'parent_cost_weight',0.1,'time_price_km_s',0.3,'time_reserve',0.1,'no_event_cost_km_s',2,'estimate_seconds',1,'min_leg_s',10800, ...
 'absorb_miss_km',2000,'absorb_residual_km',1,'absorb_max_extra_km_s',0.3,'absorb_candidates',3, ...
 'absorb_burns',2,'absorb_seconds',5,'absorb_newton_iterations',12,'absorb_newton_km',0.1,'tail_iterations',48,'tail_burns',4,'tail_seconds',6, ...
 'b_share',0.3,'heuristic_kind',1,'stop_on_complete',0,'root_service_every',6,'beam_layers',8,'per_layer',3,'root_keep',4);
if nargin>0
 names=fieldnames(overrides);
 assert(all(ismember(names,fieldnames(c))),'ctocscreen:v4:config','Unknown V4 option.');
 for k=1:numel(names), c.(names{k})=overrides.(names{k}); end
end
names=fieldnames(c);
for k=1:numel(names)
 if strcmp(names{k},'heuristic_kind'), continue; end
 validateattributes(c.(names{k}),{'double'},{'real','finite','nonnegative'});
end
% heuristic_kind: 1 or 'events' = two-body crossing estimate, 2 or 'lambert'.
if isnumeric(c.heuristic_kind), kinds={'events','lambert'}; c.heuristic_kind=kinds{c.heuristic_kind}; end
assert(ismember(c.heuristic_kind,{'events','lambert'}));
assert(c.budget_s>0&&c.root_count>=1&&c.beam_width>=2);
assert(c.search_radius_km>0&&c.search_radius_km<=1);
% Model constraints sit strictly inside the replay acceptance limits.
assert(c.model_radius_km>0&&c.model_radius_km<c.search_radius_km);
assert(c.model_height_margin_km>c.height_margin_km&&c.sma_margin_km>0&&c.sma_margin_km<10);
assert(c.rebase_limit>=1&&c.rebase_gap_km>0&&c.rebase_gap_km<c.search_radius_km-c.model_radius_km);
assert(c.shared_attempts>=1&&c.shared_attempts==round(c.shared_attempts));
assert(c.search_max_dv_km_s==6.1&&c.notify_dv_km_s==8);
assert(c.eccentricity_limit<.001&&c.exploration>0&&c.exploration<1);
assert(numel(c.scope_seconds)==3&&all(c.scope_seconds>0));
assert(c.trust_min<c.trust_initial&&c.trust_initial<=c.trust_max);
end
