function report=check_v3_construction(label)
%CHECK_V3_CONSTRUCTION Restricted real workflow check, not a performance batch.
if nargin<1, label=char(datetime('now','Format','yyyyMMdd_HHmmss')); end
assert(~isempty(regexp(label,'^[A-Za-z0-9_-]+$','once')),'ctocscreen:v3:label','Invalid run label.');
sim=fileparts(fileparts(mfilename('fullpath'))); addpath(fullfile(sim,'src'));
eph=ctocscreen.v3LoadTargetEphemeris(fullfile(sim,'runs','v3','preprocessing', ...
 'targets_20260923_release','target_ephemeris.mat'));
source=fullfile(sim,'runs','v3','search','v3_core_480_02','elite.mat'); loaded=load(source,'elite');
c=ctocscreen.v3Defaults(struct('budget_s',35,'seed',101,'root_count',1,'colony_count',2, ...
 'beam_width',3,'completion_beam_width',3,'completion_outputs',2,'completion_steps',2, ...
 'actions_per_node',3,'beam_seconds',.1,'completion_seconds',.1,'joint_seconds',.01, ...
 'joint_iterations',1,'replan_enabled',false, ...
 'guided_attempts',2,'guided_branches',2,'time_grid_count',3,'time_refine_iterations',1, ...
 'initial_candidates',{{loaded.elite.schedule}}));
folder=fullfile(sim,'runs','v3','search',label); state=ctocscreen.v3Search(folder,eph,c);
report=struct('source_file',source,'folder',folder,'nominal_budget_s',c.budget_s, ...
 'elapsed_s',state.elapsed_s,'budget_overrun_s',state.budget_overrun_s,'iterations',state.iteration, ...
 'joint_calls',numel(state.history),'directed_replans',numel(state.replan_history), ...
 'fresh_queue_count',numel(state.fresh_queue),'recovery_count',numel(state.recovery_pool), ...
 'visit_count',0,'total_dv_km_s',Inf,'result','no_independent_elite','official_alignment_verified',false);
if ~isempty(state.elite)
 report.visit_count=state.elite.verification.visit_count; report.total_dv_km_s=state.elite.verification.total_dv_km_s;
 if report.total_dv_km_s<loaded.elite.verification.total_dv_km_s-1e-9
  report.result='independent_nominal_j2_improvement';
 else
  report.result='retained_feasible_seed';
 end
end
save(fullfile(folder,'construction_check.mat'),'report'); disp(report);
end
